### ISSUE TITLE
Update documentation to reduce the entry threshold (simplified).

### ISSUE THREAD

**Issue by VictorV96** [tinode/tinode.github.io#1] opened 2019-06-24 12:02 UTC
Simplification methods:
**1) Create a test server (or use the current)**
1.1) Print the api key for the test server in the documentation.
1.3) Correct the error in the initial template on line 33 (`* me.subscribe ({get: {desc: {}, sub: {}} *);`). `* ===}`

**2) Write the simplest examples of the basis of the messenger:**
2.1) Login / Registration
2.2) Getting the list of contacts (right column in the web version) and their ID.
2.3) Sending a message to a user / group by his ID.
2.4) Sending a file to a user / group.
2.5) Getting a list of messages.
2.6) Obtaining information about the user by his ID.
2.7) Delete Editing.

If possible, add your instructions gradually adding new information. I will not be able to do this, since I myself did not understand your system.

**Comment by or-else** [comment] 2019-06-27 01:07
Duplicate of https://github.com/tinode/tinode-js/issues/25

**Closed as completed by or-else** 2019-06-27 01:07 UTC
Labels: duplicate
